### ISSUE TITLE
Listes déroulantes liées du choix de parcours.

### ISSUE THREAD

**Issue by cGuille** [TEA-ebook/help-center#33]
Quand on arrive sur la page d'accueil, la liste déroulante `J'achète sur` est positionnée sur `web`, mais on ne peut pas choisir le support de lecture (liste déroulante `Je lis sur`).

Si j'achète sur web, je ne vais pas forcément aller cliquer sur la liste déroulante pour sélectionner l'item déjà sélectionné, et je ne comprendrai pas pourquoi il n'y a rien dans la suite du formulaire.

Donc :
- soit on pré-sélectionne des valeurs et tout doit être accessible dès le début ;
- soit on ne pré-sélectionne **rien** et à ce moment là plutôt que d'avoir `…` à la place d'une liste déroulante et un texte `Je me rends sur la page` sans rien en-dessous, on laisse les éléments d’interaction affichés en leur donnant une apparence désactivée.

**Comment by fsechaud** [comment]
Pour être totalement franche, je voulais faire la première solution, mais j'ai pas réussi à le faire comme je voulais. Donc j'ai trouvé une solution intermédiaire, en attendant de pouvoir me re-pencher sur le problème.

**Comment by fsechaud** [comment]
Pour l'instant, j'ai choisi la solution 2

**Comment by cGuille** [comment]
C'est déjà beaucoup mieux je trouve !

Deux choses à améliorer pour moi :
- [ ] Quand il n'y a qu'un choix dans la liste déroulante (si on choisit une appli mobile), il faudrait qu'il n'y ait pas de liste déroulante ; pas urgent mais ça me parait quand-même mieux.
- [x] Quand on choisit « j'achète sur une liseuse », c'est la Cybook qui est pré-sélectionnée. Ça serait mieux de mettre PocketBook V5 puisque c'est ce qu'on compte avoir en plus grande quantité. Ça devrait être moins lourd à faire que le point précédent et ça peut à mon avis être fait dans #35.

**Comment by fsechaud** [comment]
- C'est vrai. J'essayerais de regarder ça à l'occas.
- Effectivement, c'est assez simple suffit de changer l'ordre des choix dans le js. Je fais ça.

**Comment by fsechaud** [comment]
Done pour l'ordre des liseuses.
