### ISSUE TITLE
Améliorer la popin d'info sur les versions d'applis / FW

### ISSUE THREAD

**Issue by cGuille** [TEA-ebook/help-center#45]
Cette popin s'affiche au passage de la souris sur un `span.info` qui contient juste un `?` et disparait / clignote dès que je bouge mon curseur. C'est pas accessible du tout et franchement désagréable même pour un internaute chevronné.

**Comment by astranchet** [comment]
Agreed, ça devrait être un lien vers une page spécifique.
Je crois qu'on en avait parlé avec Florie lors de la refonte de la FAQ (où
cette documentation est utile à plusieurs endroits)

Le 2 octobre 2015 23:03, Guillaume Charmetant notifications@github.com a
écrit :

> Cette popin s'affiche au passage de la souris sur un span.info qui
> contient juste un ? et disparait / clignote dès que je bouge mon curseur.
> C'est pas accessible du tout et franchement désagréable même pour un
> internaute chevronné.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEA-ebook/help-center/issues/45.

## 

Anne-Sophie Tranchet
TEA, The Ebook Alternative
09.72.33.50.06
